"""Add unique constraint on embeddings (entity_id, entity_type, tenant_id)

Revision ID: 19d64ee777c8
Revises: 2fd15f8c7ef4
Create Date: 2025-10-06 12:03:34.099768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19d64ee777c8'
down_revision: Union[str, Sequence[str], None] = '2fd15f8c7ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.create_index('ix_embeddings_tenant_entity', ['tenant_id', 'entity_id', 'entity_type'], unique=False)
        batch_op.create_unique_constraint('uq_embeddings_entity_tenant', ['entity_id', 'entity_type', 'tenant_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_embeddings_entity_tenant', type_='unique')
        batch_op.drop_index('ix_embeddings_tenant_entity')

    # ### end Alembic commands ###
