"""Add document_processing table

Revision ID: 1ad2d49e160d
Revises: fb5da64014df
Create Date: 2025-10-05 12:22:11.498760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ad2d49e160d'
down_revision: Union[str, Sequence[str], None] = 'fb5da64014df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_processing',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('processing_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_processing', schema=None) as batch_op:
        batch_op.create_index('ix_document_processing_completed_at', ['completed_at'], unique=False)
        batch_op.create_index('ix_document_processing_document_id', ['document_id'], unique=False)
        batch_op.create_index('ix_document_processing_started_at', ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_processing_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_processing_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_document_processing_tenant_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index('ix_document_processing_tenant_type', ['tenant_id', 'processing_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_processing', schema=None) as batch_op:
        batch_op.drop_index('ix_document_processing_tenant_type')
        batch_op.drop_index('ix_document_processing_tenant_status')
        batch_op.drop_index(batch_op.f('ix_document_processing_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_document_processing_status'))
        batch_op.drop_index('ix_document_processing_started_at')
        batch_op.drop_index('ix_document_processing_document_id')
        batch_op.drop_index('ix_document_processing_completed_at')

    op.drop_table('document_processing')
    # ### end Alembic commands ###
