"""Add saved_searches table

Revision ID: 1c4c2a91968c
Revises: e3ee7c7e51f2
Create Date: 2025-10-13 04:45:54.260056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c4c2a91968c'
down_revision: Union[str, Sequence[str], None] = 'e3ee7c7e51f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_searches',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_alert', sa.Boolean(), nullable=False),
    sa.Column('alert_frequency', sa.String(length=20), nullable=False),
    sa.Column('next_alert_at', sa.DateTime(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('shared_with_users', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('last_result_count', sa.Integer(), nullable=False),
    sa.Column('new_results_since_last_run', sa.Integer(), nullable=False),
    sa.Column('average_result_count', sa.Float(), nullable=False),
    sa.Column('average_execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.create_index('idx_saved_searches_alert_scheduling', ['is_alert', 'next_alert_at'], unique=False)
        batch_op.create_index('idx_saved_searches_name_tenant', ['tenant_id', 'name'], unique=False)
        batch_op.create_index('idx_saved_searches_tenant_created_by', ['tenant_id', 'created_by'], unique=False)
        batch_op.create_index('idx_saved_searches_tenant_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_searches_is_alert'), ['is_alert'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_searches_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_searches_next_alert_at'), ['next_alert_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_searches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_searches_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_suspicious'))
        batch_op.create_index(batch_op.f('ix_audit_logs_suspicious'), ['suspicious'], unique=False)

    with op.batch_alter_table('query_expansions', schema=None) as batch_op:
        batch_op.alter_column('usage_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query_expansions', schema=None) as batch_op:
        batch_op.alter_column('usage_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_suspicious'))
        batch_op.create_index(batch_op.f('ix_audit_logs_suspicious'), ['suspicious', 'event_timestamp'], unique=False)

    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_searches_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_saved_searches_status'))
        batch_op.drop_index(batch_op.f('ix_saved_searches_next_alert_at'))
        batch_op.drop_index(batch_op.f('ix_saved_searches_name'))
        batch_op.drop_index(batch_op.f('ix_saved_searches_is_alert'))
        batch_op.drop_index('idx_saved_searches_tenant_status')
        batch_op.drop_index('idx_saved_searches_tenant_created_by')
        batch_op.drop_index('idx_saved_searches_name_tenant')
        batch_op.drop_index('idx_saved_searches_alert_scheduling')

    op.drop_table('saved_searches')
    # ### end Alembic commands ###
