"""Make ip_address and user_agent nullable in audit_logs

Revision ID: 34c03f3fecb4
Revises: 1ad2d49e160d
Create Date: 2025-10-05 13:44:03.418007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34c03f3fecb4'
down_revision: Union[str, Sequence[str], None] = '1ad2d49e160d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=postgresql.INET(),
               nullable=True)
        batch_op.alter_column('user_agent',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('user_agent',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('ip_address',
               existing_type=postgresql.INET(),
               nullable=False)

    # ### end Alembic commands ###
