"""Expand profile embeddings to 3072

Revision ID: e84203120131
Revises: 19d64ee777c8
Create Date: 2025-10-09 01:43:21.683339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'e84203120131'
down_revision: Union[str, Sequence[str], None] = '19d64ee777c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('overall_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               existing_nullable=True,
               postgresql_using="""
               CASE
                   WHEN overall_embedding IS NULL THEN NULL
                   ELSE (
                       overall_embedding::real[] ||
                       array_fill(0::real, ARRAY[3072 - array_length(overall_embedding::real[], 1)])
                   )::vector(3072)
               END
               """)
        batch_op.alter_column('skills_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               existing_nullable=True,
               postgresql_using="""
               CASE
                   WHEN skills_embedding IS NULL THEN NULL
                   ELSE (
                       skills_embedding::real[] ||
                       array_fill(0::real, ARRAY[3072 - array_length(skills_embedding::real[], 1)])
                   )::vector(3072)
               END
               """)
        batch_op.alter_column('experience_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               existing_nullable=True,
               postgresql_using="""
               CASE
                   WHEN experience_embedding IS NULL THEN NULL
                   ELSE (
                       experience_embedding::real[] ||
                       array_fill(0::real, ARRAY[3072 - array_length(experience_embedding::real[], 1)])
                   )::vector(3072)
               END
               """)
        batch_op.alter_column('summary_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               existing_nullable=True,
               postgresql_using="""
               CASE
                   WHEN summary_embedding IS NULL THEN NULL
                   ELSE (
                       summary_embedding::real[] ||
                       array_fill(0::real, ARRAY[3072 - array_length(summary_embedding::real[], 1)])
                   )::vector(3072)
               END
               """)

    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('summary_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
        batch_op.alter_column('experience_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
        batch_op.alter_column('skills_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
        batch_op.alter_column('overall_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)

    # ### end Alembic commands ###
